import { describe, expect, it } from "vitest";

import {
  MASK_FUNCTIONS,
  TOTAL_CODEWORDS,
  VERSIONS_M,
  buildDataCodewords,
  chooseVersion,
  dataCodewordCount,
  encodeQr,
  formatInfoBits,
  interleaveCodewords,
  maskPenalty,
  moduleCountForVersion,
  qrPathData,
  qrViewBoxSize,
  rsEncode,
  versionInfoBits,
} from "./qr";

/**
 * How these fixtures were produced, and why they can be trusted.
 *
 * Every matrix below was generated by `encodeQr` and then compared, module for module, with the
 * output of the `qrcode` npm package (an independent, widely deployed encoder) run offline in a
 * scratch directory — it is deliberately not a dependency of this project. The comparison covered
 * both fixtures here plus eleven other payloads (1 to 213 bytes, ASCII and multi-byte UTF-8) at
 * every one of the eight mask patterns, with the reference forced into byte mode so the two
 * encoders are answering the same question: 96 forced-mask symbols, all identical.
 *
 * The format- and version-information words below are the published ISO/IEC 18004 values and were
 * checked against the same reference. So a regression here is a regression in this file, not a
 * disagreement about what a QR symbol is. The tests never decode: a decoder written alongside an
 * encoder only proves the two agree with each other.
 */

/** "bank rock", mask pattern 3 — version 1, the smallest symbol this module emits. */
const SHORT_TEXT = "bank rock";
const SHORT_MASK = 3;
const SHORT_MATRIX: readonly string[] = [
  "111111101000001111111",
  "100000101010101000001",
  "101110100110101011101",
  "101110101101101011101",
  "101110100111001011101",
  "100000100011101000001",
  "111111101010101111111",
  "000000001101100000000",
  "101101110011101001011",
  "000000000101100110101",
  "100111101101010100011",
  "111110010101000101011",
  "010011100010101010000",
  "000000001001000010100",
  "111111101111101110100",
  "100000101010000111110",
  "101110100110101001100",
  "101110101011001100110",
  "101110101010101001000",
  "100000100010010001001",
  "111111101100010010100",
];

/**
 * The exact shape the give link takes: `/rock/<id>?give=<address>`, 77 characters.
 * The address literal is fine here — the D-015 "no address outside lib/chain" check excludes
 * `*.test.ts`, and a fixture has to be a fixed input.
 */
const GIVE_URL = "https://bank-rock.com/rock/12?give=0x1234567890AbcdEF1234567890aBcdef12345678";
const GIVE_URL_MASK = 2;
const GIVE_URL_MATRIX: readonly string[] = [
  "1111111001111110000101010010001111111",
  "1000001001110011100010001101101000001",
  "1011101010011000100111100011101011101",
  "1011101010111010111000101111001011101",
  "1011101010100101110111010000101011101",
  "1000001011010110001001100111101000001",
  "1111111010101010101010101010101111111",
  "0000000010000101001111110000100000000",
  "1011111001111110001010111100101111100",
  "0100100001011011111100010110001101110",
  "0001111010000110000000000101001001011",
  "0111110110100110100111111011100101001",
  "1001011101010010111010001101011010111",
  "1110000100011110010111010000100100010",
  "0111111010000011010010101111011111001",
  "1101010000100011111001011010011110010",
  "1000111100100011100110001101111010111",
  "0010110011000101001100110110001101110",
  "0011011010000111101010101111101110011",
  "0100000011011001001011111000011001001",
  "1011001001110001110000000111111010100",
  "0110110100101000000111110100100001010",
  "0100001101011011101011000001111111001",
  "0010110000011110000111110001100110000",
  "1110101001010111001010011100101010111",
  "1101000110011001110101100010010101000",
  "1001101010111100001001000101010011011",
  "1010110000100110101011101010000000011",
  "1010111111000110111000001111111111010",
  "0000000010001010010111111101100011010",
  "1111111001110011010010000000101010101",
  "1000001011001100011111000011100011011",
  "1011101010001011100110011101111110111",
  "1011101011010101001101110110111011001",
  "1011101011111001101010001111100000011",
  "1000001000111001000101001010101010001",
  "1111111010111101111010001111011011111",
];

/** The published level-M format words, mask 0 through 7 (ISO/IEC 18004 Table 25). */
const FORMAT_WORDS_M: readonly string[] = [
  "101010000010010",
  "101000100100101",
  "101111001111100",
  "101101101001011",
  "100010111111001",
  "100000011001110",
  "100111110010111",
  "100101010100000",
];

/** The published version-information words for the versions that carry one (ISO Table 26). */
const VERSION_WORDS: Readonly<Record<number, number>> = {
  7: 0x07c94,
  8: 0x085bc,
  9: 0x09a99,
  10: 0x0a4d3,
};

function rows(text: string, mask?: number): string[] {
  const matrix = encodeQr(text, mask === undefined ? {} : { mask });
  return matrix.modules.map((row) => row.map((module) => (module ? "1" : "0")).join(""));
}

describe("version tables", () => {
  it("agrees with the total codeword count for every version it offers", () => {
    for (const spec of VERSIONS_M) {
      const total =
        spec.group1Blocks * (spec.group1Data + spec.ecPerBlock) +
        spec.group2Blocks * (spec.group2Data + spec.ecPerBlock);
      expect(total).toBe(TOTAL_CODEWORDS[spec.version - 1]);
    }
  });

  it("has a second group that is always exactly one codeword longer", () => {
    for (const spec of VERSIONS_M) {
      if (spec.group2Blocks === 0) continue;
      expect(spec.group2Data).toBe(spec.group1Data + 1);
    }
  });

  it("sizes the symbol as 4 * version + 17", () => {
    expect(moduleCountForVersion(1)).toBe(21);
    expect(moduleCountForVersion(5)).toBe(37);
    expect(moduleCountForVersion(10)).toBe(57);
  });
});

describe("format and version information", () => {
  it("produces the published level-M format word for every mask", () => {
    for (let mask = 0; mask < 8; mask++) {
      expect(formatInfoBits(mask).toString(2).padStart(15, "0")).toBe(FORMAT_WORDS_M[mask]);
    }
  });

  it("produces the published version words for versions 7 to 10", () => {
    for (const [version, word] of Object.entries(VERSION_WORDS)) {
      expect(versionInfoBits(Number(version))).toBe(word);
    }
  });
});

describe("Reed-Solomon", () => {
  it("returns exactly the requested number of check codewords", () => {
    for (const ecLen of [10, 16, 18, 22, 24, 26]) {
      expect(rsEncode(new Uint8Array([1, 2, 3, 4]), ecLen)).toHaveLength(ecLen);
    }
  });

  it("is linear over GF(256): encoding zeros yields zeros", () => {
    const ec = rsEncode(new Uint8Array(16), 10);
    expect([...ec]).toEqual(new Array(10).fill(0));
  });

  it("changes the check codewords when any data byte changes", () => {
    const a = rsEncode(new Uint8Array([0, 0, 0, 1]), 10);
    const b = rsEncode(new Uint8Array([0, 0, 0, 2]), 10);
    expect([...a]).not.toEqual([...b]);
  });
});

describe("data codewords", () => {
  it("writes the byte-mode indicator, the length and then the payload", () => {
    const spec = VERSIONS_M[0];
    const codewords = buildDataCodewords(new Uint8Array([0xaa, 0xbb]), spec);
    // 0100 (byte mode), the 8-bit length 0000_0010, the two payload bytes, then the terminator —
    // none of which is byte-aligned, so the codewords are the bit stream cut into eights.
    expect([...codewords.slice(0, 5)]).toEqual([0x40, 0x2a, 0xab, 0xb0, 0xec]);
  });

  it("fills the rest of the block with the alternating pad codewords", () => {
    const spec = VERSIONS_M[0];
    const codewords = buildDataCodewords(new Uint8Array([0x01]), spec);
    expect(codewords).toHaveLength(dataCodewordCount(spec));
    const pad = [...codewords.slice(3)];
    expect(pad).toEqual(
      pad.map((_, index) => (index % 2 === 0 ? 0xec : 0x11)),
    );
  });

  it("interleaves to the version's full codeword count", () => {
    for (const spec of VERSIONS_M) {
      const data = buildDataCodewords(new Uint8Array(4).fill(0x42), spec);
      expect(interleaveCodewords(data, spec)).toHaveLength(TOTAL_CODEWORDS[spec.version - 1]);
    }
  });
});

describe("version selection", () => {
  it("picks the smallest version that holds the payload", () => {
    expect(chooseVersion(14).version).toBe(1); // v1-M holds 16 data codewords: 4 + 8 + 14*8 bits
    expect(chooseVersion(15).version).toBe(2);
    expect(chooseVersion(77).version).toBe(5); // the give-link URL
    expect(chooseVersion(213).version).toBe(10);
  });

  it("refuses a payload larger than version 10 rather than truncating it", () => {
    expect(() => chooseVersion(214)).toThrow(/exceeds version 10/);
    expect(() => encodeQr("x".repeat(214))).toThrow(/exceeds version 10/);
  });

  it("refuses an empty payload and an out-of-range mask", () => {
    expect(() => encodeQr("")).toThrow(/empty/);
    expect(() => encodeQr("hello", { mask: 8 })).toThrow(/mask must be an integer/);
    expect(() => encodeQr("hello", { mask: -1 })).toThrow(/mask must be an integer/);
  });
});

describe("known-good symbols", () => {
  it("reproduces the version-1 fixture module for module", () => {
    expect(rows(SHORT_TEXT, SHORT_MASK)).toEqual([...SHORT_MATRIX]);
  });

  it("reproduces the give-link fixture, including the mask it selects", () => {
    const matrix = encodeQr(GIVE_URL);
    expect(matrix.version).toBe(5);
    expect(matrix.size).toBe(37);
    expect(matrix.mask).toBe(GIVE_URL_MASK);
    expect(rows(GIVE_URL)).toEqual([...GIVE_URL_MATRIX]);
  });

  it("is deterministic", () => {
    expect(rows(GIVE_URL)).toEqual(rows(GIVE_URL));
  });

  it("changes when the address in the link changes", () => {
    const other = GIVE_URL.replace("give=0x1", "give=0x2");
    expect(rows(other)).not.toEqual(rows(GIVE_URL));
  });
});

describe("symbol structure", () => {
  const matrix = encodeQr(GIVE_URL);

  it("is a square matrix of the version's module count", () => {
    expect(matrix.modules).toHaveLength(matrix.size);
    for (const row of matrix.modules) expect(row).toHaveLength(matrix.size);
    expect(matrix.size).toBe(moduleCountForVersion(matrix.version));
  });

  it("carries a finder pattern in three corners and none in the fourth", () => {
    const finder = (top: number, left: number) => {
      const ring = [0, 6];
      for (const r of ring) {
        for (let c = 0; c < 7; c++) {
          if (!matrix.modules[top + r][left + c]) return false;
          if (!matrix.modules[top + c][left + r]) return false;
        }
      }
      for (let r = 2; r <= 4; r++) {
        for (let c = 2; c <= 4; c++) if (!matrix.modules[top + r][left + c]) return false;
      }
      // The ring must be separated from the core by a light square.
      for (let c = 1; c <= 5; c++) if (matrix.modules[top + 1][left + c]) return false;
      return true;
    };
    const last = matrix.size - 7;
    expect(finder(0, 0)).toBe(true);
    expect(finder(0, last)).toBe(true);
    expect(finder(last, 0)).toBe(true);
    expect(finder(last, last)).toBe(false);
  });

  it("alternates the timing patterns and sets the always-dark module", () => {
    for (let i = 8; i < matrix.size - 8; i++) {
      expect(matrix.modules[6][i]).toBe(i % 2 === 0);
      expect(matrix.modules[i][6]).toBe(i % 2 === 0);
    }
    expect(matrix.modules[matrix.size - 8][8]).toBe(true);
  });

  it("uses between a third and two thirds dark modules, whatever the mask", () => {
    for (let mask = 0; mask < 8; mask++) {
      const masked = encodeQr(GIVE_URL, { mask });
      const dark = masked.modules.flat().filter(Boolean).length;
      const share = dark / (masked.size * masked.size);
      expect(share).toBeGreaterThan(0.33);
      expect(share).toBeLessThan(0.67);
    }
  });
});

describe("masking", () => {
  it("has eight distinct mask conditions", () => {
    const signatures = MASK_FUNCTIONS.map((fn) => {
      let bits = "";
      for (let r = 0; r < 6; r++) for (let c = 0; c < 6; c++) bits += fn(r, c) ? "1" : "0";
      return bits;
    });
    expect(new Set(signatures).size).toBe(8);
  });

  it("produces a different symbol for each mask", () => {
    const rendered = new Set<string>();
    for (let mask = 0; mask < 8; mask++) rendered.add(rows(GIVE_URL, mask).join("\n"));
    expect(rendered.size).toBe(8);
  });

  it("selects the mask with the lowest penalty score", () => {
    const scores = [];
    for (let mask = 0; mask < 8; mask++) {
      scores.push(maskPenalty(encodeQr(GIVE_URL, { mask }).modules));
    }
    const best = scores.indexOf(Math.min(...scores));
    expect(encodeQr(GIVE_URL).mask).toBe(best);
  });

  it("penalises a blank field heavily and an alternating one lightly", () => {
    const size = 21;
    const blank = Array.from({ length: size }, () => new Array<boolean>(size).fill(false));
    const checker = Array.from({ length: size }, (_, r) =>
      Array.from({ length: size }, (_, c) => (r + c) % 2 === 0),
    );
    expect(maskPenalty(blank)).toBeGreaterThan(maskPenalty(checker));
  });
});

describe("svg output", () => {
  const matrix = encodeQr(GIVE_URL);

  it("draws one unit square per dark module inside a quiet zone", () => {
    const path = qrPathData(matrix);
    const dark = matrix.modules.flat().filter(Boolean).length;
    expect(path.split("M").length - 1).toBe(dark);
    expect(qrViewBoxSize(matrix)).toBe(matrix.size + 8);
  });

  it("keeps every drawn square inside the view box", () => {
    const quietZone = 4;
    const limit = qrViewBoxSize(matrix, quietZone);
    for (const move of qrPathData(matrix, quietZone).split("M").slice(1)) {
      const [x, y] = move.replace(/h1v1h-1z/, "").split(" ").map(Number);
      expect(x).toBeGreaterThanOrEqual(quietZone);
      expect(y).toBeGreaterThanOrEqual(quietZone);
      expect(x + 1).toBeLessThanOrEqual(limit - quietZone);
      expect(y + 1).toBeLessThanOrEqual(limit - quietZone);
    }
  });

  it("emits nothing outside the module grid for an empty quiet zone", () => {
    expect(qrViewBoxSize(matrix, 0)).toBe(matrix.size);
  });
});
