/**
 * Regenerates `mcp/registry-abi.ts` from the ABI that `contracts/` exports.
 *
 * The MCP server must not carry a hand-maintained copy of the registry interface: a drifted ABI
 * decodes chain state into wrong values, and wrong values presented to an AI agent are exactly
 * what decision D-019 exists to prevent. This script is the `prebuild` step, so `npm run build`
 * always compiles against the current ABI.
 *
 * The generated file is committed so that `npm start` (ts-node, no build step) works from a
 * fresh checkout without first compiling the contracts.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const mcpRoot = path.resolve(here, "..");
const source = path.resolve(mcpRoot, "..", "contracts", "abi", "BankRockRegistry.json");
const target = path.join(mcpRoot, "registry-abi.ts");

if (!fs.existsSync(source)) {
  if (fs.existsSync(target)) {
    console.warn(`[sync-abi] ${path.relative(mcpRoot, source)} is missing; keeping the committed registry-abi.ts.`);
    process.exit(0);
  }
  console.error(
    `[sync-abi] ${source} not found and no committed registry-abi.ts to fall back on.\n` +
      `           Run "npm run compile" in ../contracts first.`,
  );
  process.exit(1);
}

const { abi } = JSON.parse(fs.readFileSync(source, "utf8"));

const contents =
  `// Generated by scripts/sync-abi.mjs from ../contracts/abi/BankRockRegistry.json.\n` +
  `// Do not edit by hand: run "npm run build" (or "node scripts/sync-abi.mjs") to refresh.\n` +
  `export const registryAbi = ${JSON.stringify(abi, null, 2)} as const;\n`;

const previous = fs.existsSync(target) ? fs.readFileSync(target, "utf8") : null;
if (previous === contents) {
  console.log("[sync-abi] registry-abi.ts is up to date.");
} else {
  fs.writeFileSync(target, contents);
  console.log(`[sync-abi] wrote registry-abi.ts (${abi.length} ABI entries).`);
}
